### ISSUE TITLE
Ads skipper doesn't work in Youtube Music

### ISSUE THREAD

**Issue by deeffest** [Thunderarea/music-mode-for-youtube#26]
When ads appear, the ad-skipper displays the message `mutation.target.playVideo is not a function` in the console and as a consequence ads are not skipped.
I fixed this by changing lines in findAndSkipAds 
```mutation.target.playVideo();``` 
to 
```mutation.target.querySelector("video").play();```
 in adSkipper.js

**Comment by Thunderarea** [comment]
Thank you very much for the report and the solution that you suggest. I will take a look at it the next days.

**Comment by Thunderarea** [comment]
I have looked at the issue that you describe but it seems that it is working fine (YouTube Music on Chrome). Can you give me more details where this error happens?

**Comment by deeffest** [comment]
The problem was most likely in my portable Сhrome which has not been updated for a long time, after updating to the latest version the extension works as it should
