### ISSUE TITLE
Firefox: Icon doesn't auto appear on YT bar when page loads

### ISSUE THREAD

**Issue by godzfire** [Thunderarea/music-mode-for-youtube#31]
Using the current version of Firefox and music mode, if you load a YouTube page, it will not actually work until you manually hit the extension button located with the other extension buttons. 

It will then load and block the video, and the music mode icon will show up in the YouTube player UI. However each time you refresh the page, it will forget this setting, and revert back. And you'll have to click the button again or to show up.

**Comment by Jvascs** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by Thunderarea** [comment]
This is a Firefox problem that I remember I also had when I used the extension for the first time in Firefox. If I remember correctly the solution is to right-click on the extension's icon in the browser's toolbar and click the option "Manage extension". In the page that will open enable the access to YouTube and YouTube music (and any other site that you need)
![image](https://github.com/user-attachments/assets/6663b39f-9393-45e0-84de-5ca5959ca584)

Please, let me know if it will fix the issue.
