### ISSUE TITLE
Add playlist next/prev buttons to Android Firefox

### ISSUE THREAD

**Issue by thebestnom** [Thunderarea/music-mode-for-youtube#33]
Amazing extension, the only problem I have is that the next and prev doesn't exists so we can't control from outside the browser the music playing
I know this is a general youtube for firefox (at least for android) thing, but adding this would make life so much better! (Maybe even sending a custom browser in the http request to get chrome version would be enough)

**Comment by Thunderarea** [comment]
Thank you for the suggestion! However, this is something out of the scope of the extension and I even don't know if it is technically possible.
